var data = [
  {
    name: "A",
    type: "letter",
    img: "photos/a.png",
    audio: "audios/A.wav",
  },
  {
    name: "B",
    type: "letter",
    img: "photos/b.png",
    audio: "audios/B.wav",
  },
  {
    name: "C",
    type: "letter",
    img: "photos/c.png",
    audio: "audios/C.wav",
  },
  {
    name: "D",
    type: "letter",
    img: "photos/d.png",
    audio: "audios/D.wav",
  },
  {
    name: "E",
    type: "letter",
    img: "photos/e.png",
    audio: "audios/E.wav",
  },
  {
    name: "F",
    type: "letter",
    img: "photos/f.png",
    audio: "audios/F.wav",
  },
  {
    name: "G",
    type: "letter",
    img: "photos/g.png",
    audio: "audios/G.wav",
  },
  {
    name: "H",
    type: "letter",
    img: "photos/h.png",
    audio: "audios/H.wav",
  },
  {
    name: "I",
    type: "letter",
    img: "photos/i.png",
    audio: "audios/I.wav",
  },
  {
    name: "J",
    type: "letter",
    img: "photos/j.png",
    audio: "audios/J.wav",
  },
  {
    name: "K",
    type: "letter",
    img: "photos/k.png",
    audio: "audios/K.wav",
  },
  {
    name: "L",
    type: "letter",
    img: "photos/l.png",
    audio: "audios/L.wav",
  },
  {
    name: "M",
    type: "letter",
    img: "photos/m.png",
    audio: "audios/M.wav",
  },
  {
    name: "N",
    type: "letter",
    img: "photos/n.png",
    audio: "audios/N.wav",
  },
  {
    name: "O",
    type: "letter",
    img: "photos/o.png",
    audio: "audios/O.wav",
  },
  {
    name: "P",
    type: "letter",
    img: "photos/p.png",
    audio: "audios/P.wav",
  },
  {
    name: "Q",
    type: "letter",
    img: "photos/q.png",
    audio: "audios/Q.wav",
  },
  {
    name: "R",
    type: "letter",
    img: "photos/r.png",
    audio: "audios/R.wav",
  },
  {
    name: "S",
    type: "letter",
    img: "photos/s.png",
    audio: "audios/S.wav",
  },

  {
    name: "T",
    type: "letter",
    img: "photos/t.png",
    audio: "audios/T.wav",
  },
  {
    name: "U",
    type: "letter",
    img: "photos/u.png",
    audio: "audios/U.wav",
  },
  {
    name: "V",
    type: "letter",
    img: "photos/v.png",
    audio: "audios/V.wav",
  },
  {
    name: "W",
    type: "letter",
    img: "photos/w.png",
    audio: "audios/W.wav",
  },
  {
    name: "X",
    type: "letter",
    img: "photos/x.png",
    audio: "audios/X.wav",
  },
  {
    name: "Y",
    type: "letter",
    img: "photos/y.png",
    audio: "audios/Y.wav",
  },
  {
    name: "Z",
    type: "letter",
    img: "photos/z.png",
    audio: "audios/Z.wav",
  },
  // start animals object
  {
    name: "Cat",
    type: "animal",
    img: "photos/cat.jpg",
    audio: "audios/cat.wav",
  },
  {
    name: "Dog",
    type: "animal",
    img: "photos/dog.jpg",
    audio: "audios/dog.wav",
  },
  {
    name: "Horse",
    type: "animal",
    img: "photos/horse.jpg",
    audio: "audios/horse.wav",
  },
  {
    name: "Fox",
    type: "animal",
    img: "photos/fox.jpg",
    audio: "audios/fox.mp3",
  },
  {
    name: "Zebra",
    type: "animal",
    img: "photos/zebra.jpg",
    audio: "audios/zebra.wav",
  },
  {
    name: "Jaguar",
    type: "animal",
    img: "photos/jaguar.jpg",
    audio: "audios/jaguar.wav",
  },
  {
    name: "Snake",
    type: "animal",
    img: "photos/snake.jpg",
    audio: "audios/snake.mp3",
  },
  {
    name: "Rooster",
    type: "animal",
    img: "photos/rooster.jpg",
    audio: "audios/rooster.wav",
  },
  {
    name: "Lions",
    type: "animal",
    img: "photos/lions.jpg",
    audio: "audios/lion.wav",
  },
  {
    name: "Dolphin",
    type: "animal",
    img: "photos/dolphin.jpg",
    audio: "audios/dolphin.wav",
  },
  {
    name: "Parrot",
    type: "animal",
    img: "photos/parrot.jpg",
    audio: "audios/parrot.mp3",
  },
  {
    name: "Koala",
    type: "animal",
    img: "photos/koala.jpg",
    audio: "audios/koala.wav",
  },
  // start numbers object
  {
    name: "Zero",
    type: "number",
    img: "photos/0.png",
    audio: "audios/0.wav",
  },

  {
    name: "One",
    type: "number",
    img: "photos/1.png",
    audio: "audios/one.wav",
  },
  {
    name: "Two",
    type: "number",
    img: "photos/2.png",
    audio: "audios/two.wav",
  },
  {
    name: "Three",
    type: "number",
    img: "photos/3.png",
    audio: "audios/three.wav",
  },
  {
    name: "Four",
    type: "number",
    img: "photos/4.png",
    audio: "audios/four.wav",
  },
  {
    name: "Five",
    type: "number",
    img: "photos/5.png",
    audio: "audios/five.wav",
  },
  {
    name: "Sex",
    type: "number",
    img: "photos/6.png",
    audio: "audios/six.wav",
  },
  {
    name: "Seven",
    type: "number",
    img: "photos/7.png",
    audio: "audios/seven.wav",
  },
  {
    name: "Eight",
    type: "number",
    img: "photos/8.png",
    audio: "audios/eight.wav",
  },
  {
    name: "Nine",
    type: "number",
    img: "photos/9.png",
    audio: "audios/nine.wav",
  },
  {
    name: "Ten",
    type: "number",
    img: "photos/10.png",
    audio: "audios/ten.wav",
  },
  {
    name: "Eleven",
    type: "number",
    img: "photos/11.png",
    audio: "audios/11.wav",
  },
  {
    name: "Twelve",
    type: "number",
    img: "photos/12.png",
    audio: "audios/12.wav",
  },
  {
    name: "Thirteen",
    type: "number",
    img: "photos/13.png",
    audio: "audios/13.wav",
  },
  {
    name: "Fourteen",
    type: "number",
    img: "photos/14.png",
    audio: "audios/14.wav",
  },
  {
    name: "Fifteen",
    type: "number",
    img: "photos/15.png",
    audio: "audios/15.wav",
  },
  {
    name: "Sixteen",
    type: "number",
    img: "photos/16.png",
    audio: "audios/16.wav",
  },
  {
    name: "Seventeen",
    type: "number",
    img: "photos/17.png",
    audio: "audios/17.wav",
  },
  {
    name: "Eighteen",
    type: "number",
    img: "photos/18.png",
    audio: "audios/18.wav",
  },
  {
    name: "Nineteen",
    type: "number",
    img: "photos/19.png",
    audio: "audios/19.wav",
  },
  {
    name: "Twenty",
    type: "number",
    img: "photos/20.png",
    audio: "audios/20.wav",
  },
];
